version: "3"
services:
  spate:
    build: .
    image: spate:latest
  # cli:
  #   build: $GOPATH/src/github.com/olesho/spate/cli
  #   environment:
  #     - MICRO_REGISTRY
  #     - HOST
  #     - PORT
  #     - SECURE
  #     - FB_CALLBACK_URL
  #     - FB_ID
  #     - FB_SECRET
  #     - DOMAIN
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - spate
  endpoint:
    build: $GOPATH/src/github.com/olesho/spate/endpoint
    environment:
      - MICRO_REGISTRY
      - MICRO_REGISTRY_ADDRESS
      - MICRO_SERVER_ADDRESS=:9999
      - MICRO_SERVER_ADVERTISE=10.8.0.10:9999
      - DB_HOST
      - DB_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "9999:9999"
    network_mode: bridge
  processors:
    build: $GOPATH/src/github.com/olesho/spate/processors
    environment:
      - MICRO_REGISTRY
      - MICRO_REGISTRY_ADDRESS
      - MICRO_SERVER_ADDRESS=:9998
      - MICRO_SERVER_ADVERTISE=10.8.0.10:9997
    ports:
      - "9998:9998"
    network_mode: bridge
  subscribe:
    build: $GOPATH/src/github.com/olesho/spate/subscribe
    environment:
      - GCM_API_KEY
      - MICRO_REGISTRY
      - MICRO_REGISTRY_ADDRESS
      - MICRO_SERVER_ADDRESS=:9997
      - MICRO_SERVER_ADVERTISE=10.8.0.10:9997
    ports:
      - "9997:9997"
    network_mode: bridge
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - "mysql_data:/var/lib/mysql" # data container
    restart: always
    network_mode: bridge
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: kotyczky
      PMA_HOST: mysql
    network_mode: bridge

volumes:
 mysql_data:
   driver: local