version: "3"
services:
  spate:
    build: .
    image: spate:latest
  cli:
    build: ./cli
    environment:
      - MICRO_REGISTRY
      - HOST
      - PORT
      - SECURE
      - FB_CALLBACK_URL
      - FB_ID
      - FB_SECRET
      - DOMAIN
    ports:
      - 3000:3000
    depends_on:
      - spate
  endpoint:
    build: ./endpoint
    environment:
      - MICRO_REGISTRY
      - DB_HOST
      - DB_PORT
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    depends_on:
      - mysql
    links:
      - mysql
  processors:
    build: ./processors
    environment:
      - MICRO_REGISTRY
  subscribe:
    build: ./subscribe
    environment:
      - MICRO_REGISTRY
      - GCM_API_KEY
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
#    volumes:
#      - "mysql_data:/var/lib/mysql" # data container
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: kotyczky
      PMA_HOST: mysql

#volumes:
#  mysql_data:
#    driver: local