// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/subscribe.proto

/*
Package subscription is a generated protocol buffer package.

It is generated from these files:
	proto/subscribe.proto

It has these top-level messages:
	Subscription
	User
	SubscriptionsList
	Response
	Notification
	EmptySubscription
*/
package subscription

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Subscription struct {
	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Active bool   `protobuf:"varint,3,opt,name=active" json:"active,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Subscription) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Subscription) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Subscription) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type User struct {
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type SubscriptionsList struct {
	Response *Response       `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	List     []*Subscription `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (m *SubscriptionsList) Reset()                    { *m = SubscriptionsList{} }
func (m *SubscriptionsList) String() string            { return proto.CompactTextString(m) }
func (*SubscriptionsList) ProtoMessage()               {}
func (*SubscriptionsList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubscriptionsList) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *SubscriptionsList) GetList() []*Subscription {
	if m != nil {
		return m.List
	}
	return nil
}

type Response struct {
	Ok    bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Notification struct {
	UserId int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Body   string `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Url    string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
}

func (m *Notification) Reset()                    { *m = Notification{} }
func (m *Notification) String() string            { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()               {}
func (*Notification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Notification) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Notification) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type EmptySubscription struct {
}

func (m *EmptySubscription) Reset()                    { *m = EmptySubscription{} }
func (m *EmptySubscription) String() string            { return proto.CompactTextString(m) }
func (*EmptySubscription) ProtoMessage()               {}
func (*EmptySubscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Subscription)(nil), "subscription.Subscription")
	proto.RegisterType((*User)(nil), "subscription.User")
	proto.RegisterType((*SubscriptionsList)(nil), "subscription.SubscriptionsList")
	proto.RegisterType((*Response)(nil), "subscription.Response")
	proto.RegisterType((*Notification)(nil), "subscription.Notification")
	proto.RegisterType((*EmptySubscription)(nil), "subscription.EmptySubscription")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SubscribeService service

type SubscribeServiceClient interface {
	Create(ctx context.Context, in *Subscription, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error)
	List(ctx context.Context, in *EmptySubscription, opts ...client.CallOption) (*SubscriptionsList, error)
	Notify(ctx context.Context, in *Notification, opts ...client.CallOption) (*Response, error)
}

type subscribeServiceClient struct {
	c           client.Client
	serviceName string
}

func NewSubscribeServiceClient(serviceName string, c client.Client) SubscribeServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "subscription"
	}
	return &subscribeServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *subscribeServiceClient) Create(ctx context.Context, in *Subscription, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "SubscribeService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeServiceClient) Delete(ctx context.Context, in *User, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "SubscribeService.Delete", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeServiceClient) List(ctx context.Context, in *EmptySubscription, opts ...client.CallOption) (*SubscriptionsList, error) {
	req := c.c.NewRequest(c.serviceName, "SubscribeService.List", in)
	out := new(SubscriptionsList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscribeServiceClient) Notify(ctx context.Context, in *Notification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "SubscribeService.Notify", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SubscribeService service

type SubscribeServiceHandler interface {
	Create(context.Context, *Subscription, *Response) error
	Delete(context.Context, *User, *Response) error
	List(context.Context, *EmptySubscription, *SubscriptionsList) error
	Notify(context.Context, *Notification, *Response) error
}

func RegisterSubscribeServiceHandler(s server.Server, hdlr SubscribeServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&SubscribeService{hdlr}, opts...))
}

type SubscribeService struct {
	SubscribeServiceHandler
}

func (h *SubscribeService) Create(ctx context.Context, in *Subscription, out *Response) error {
	return h.SubscribeServiceHandler.Create(ctx, in, out)
}

func (h *SubscribeService) Delete(ctx context.Context, in *User, out *Response) error {
	return h.SubscribeServiceHandler.Delete(ctx, in, out)
}

func (h *SubscribeService) List(ctx context.Context, in *EmptySubscription, out *SubscriptionsList) error {
	return h.SubscribeServiceHandler.List(ctx, in, out)
}

func (h *SubscribeService) Notify(ctx context.Context, in *Notification, out *Response) error {
	return h.SubscribeServiceHandler.Notify(ctx, in, out)
}

func init() { proto.RegisterFile("proto/subscribe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0xa5, 0x1f, 0xaf, 0xaf, 0x5c, 0xc8, 0x0b, 0xdc, 0xf7, 0x1e, 0x36, 0x6c, 0x68, 0x66, 0xd5,
	0x55, 0x35, 0x35, 0x71, 0xe9, 0x46, 0x5d, 0x68, 0x8c, 0x8b, 0x21, 0xac, 0x0d, 0x2d, 0xd7, 0x64,
	0x42, 0x65, 0x9a, 0x99, 0x01, 0xc3, 0x1f, 0xf1, 0xf7, 0x9a, 0x8e, 0x40, 0x8a, 0xa6, 0xb8, 0x9b,
	0x33, 0x3d, 0xbd, 0xf7, 0x7c, 0x0c, 0xfc, 0xaf, 0x94, 0x34, 0xf2, 0x5c, 0xaf, 0x73, 0x5d, 0x28,
	0x91, 0x53, 0x6a, 0x31, 0xf6, 0x77, 0x17, 0x95, 0x11, 0x72, 0xc5, 0x66, 0xd0, 0x9f, 0x36, 0x30,
	0x9e, 0xc1, 0xef, 0xb5, 0x26, 0xf5, 0x2c, 0x16, 0x91, 0x13, 0x3b, 0x89, 0xc7, 0x83, 0x1a, 0xde,
	0x2f, 0xf0, 0x1f, 0xfc, 0x32, 0x72, 0x49, 0xab, 0xc8, 0x8d, 0x9d, 0xa4, 0xcb, 0x3f, 0x01, 0x8e,
	0x20, 0x98, 0x17, 0x46, 0x6c, 0x28, 0xf2, 0x62, 0x27, 0x09, 0xf9, 0x0e, 0xb1, 0x09, 0xf8, 0x33,
	0x4d, 0xaa, 0x75, 0x1c, 0x7b, 0x83, 0x61, 0x73, 0xaf, 0x7e, 0x14, 0xda, 0x60, 0x06, 0xa1, 0x22,
	0x5d, 0xc9, 0x95, 0x26, 0x4b, 0xef, 0x65, 0xa3, 0xb4, 0xa9, 0x36, 0xe5, 0xbb, 0xaf, 0xfc, 0xc0,
	0xc3, 0x14, 0xfc, 0x52, 0x68, 0x13, 0xb9, 0xb1, 0x97, 0xf4, 0xb2, 0xf1, 0x31, 0xbf, 0xb9, 0x82,
	0x5b, 0x1e, 0xbb, 0x80, 0x70, 0x3f, 0x05, 0xff, 0x80, 0x2b, 0x97, 0x76, 0x53, 0xc8, 0x5d, 0xb9,
	0xac, 0x3d, 0x92, 0x52, 0x52, 0xed, 0x3d, 0x5a, 0xc0, 0x0a, 0xe8, 0x3f, 0x49, 0x23, 0x5e, 0x44,
	0x31, 0xff, 0x39, 0x22, 0x61, 0x4a, 0x3a, 0x44, 0x54, 0x03, 0x44, 0xf0, 0x73, 0xb9, 0xd8, 0xda,
	0x80, 0xba, 0xdc, 0x9e, 0x71, 0x00, 0xde, 0x5a, 0x95, 0x91, 0x6f, 0xaf, 0xea, 0x23, 0xfb, 0x0b,
	0xc3, 0xbb, 0xd7, 0xca, 0x6c, 0x9b, 0x8a, 0xb3, 0x77, 0x17, 0x06, 0xd3, 0x7d, 0x7d, 0x53, 0x52,
	0x1b, 0x51, 0x10, 0x5e, 0x43, 0x70, 0xa3, 0x68, 0x6e, 0x08, 0x4f, 0x98, 0x1d, 0xb7, 0x04, 0xc7,
	0x3a, 0x78, 0x05, 0xc1, 0x2d, 0x95, 0x64, 0x08, 0xf1, 0x98, 0x53, 0x17, 0x76, 0xe2, 0xbf, 0x07,
	0xf0, 0x6d, 0x49, 0x93, 0x63, 0xc6, 0x37, 0xd5, 0xe3, 0x49, 0xbb, 0x2c, 0x5b, 0x33, 0xeb, 0xd4,
	0x1e, 0x6c, 0xa4, 0xdb, 0xaf, 0x1e, 0x9a, 0x41, 0xb7, 0x6b, 0xc9, 0x03, 0xfb, 0x94, 0x2f, 0x3f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x98, 0xb7, 0x93, 0xe3, 0x02, 0x00, 0x00,
}
